### ISSUE TITLE
Please add 11.4.0 Play Services

### ISSUE THREAD

**Issue by skoften** [appcelerator-modules/ti.playservices#1]
Thanks! :-)

**Comment by hansemannn** [comment]
Are those final, yet? Android API-level 27 (Android 8.1) is still in developer-preview I think

**Comment by skoften** [comment]
Oh sorry, this comments should been placed on another repo, please ignore! :-)

**Comment by hansemannn** [comment]
I don't think their repo is still maintained :-) But just out of interest: Why would you want to use something later then 11.0.2 in production?

**Comment by skoften** [comment]
Because PushWoosh deciced to use 11.4.0 in their module: https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/tree/master/Push-Notifications-Module/modules/android/com.pushwoosh.module/5.4.0/lib

And because we are also using 2 other modules (Ti.GA and Ti.DFP) that use some Google Play packages, I need to sync their versions. 

Also, 11.4.0 has been release in september: https://developers.google.com/android/guides/releases

**Comment by hansemannn** [comment]
Are those the final releases? And yeah, that's what this module will solve and and forever. No dependency-hell anymore.
