### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by mebarg** [appcelerator-modules/ti.playservices#10]
when compiling my project whit this module i gent the following error:

[ERROR] Application Installer abnormal process termination. Process exit value was 1
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/ItemListIntents;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/NoteIntents;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/ReserveIntents;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/SearchIntents;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/AccountChangeEvent;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/AccountChangeEventsRequest;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/AccountChangeEventsResponse;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/GoogleAuthException;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/GoogleAuthUtil;
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.RuntimeException: Translation has been interrupted
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:615)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:368)
[ERROR] :  	at com.android.dx.command.dexer.Main.runDx(Main.java:289)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:247)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:94)
[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:607)
[ERROR] :  	... 4 more

**Comment by hansemannn** [comment]
The error indicates that you have another module that uses play-services without the ti.playservices module, which is invalid since SDK 7. What modules do you use?

**Comment by mebarg** [comment]
modules i use:

<module platform="android">facebook</module>
        <module platform="iphone">facebook</module>
        <module platform="android">dk.napp.drawer</module>
        <module platform="iphone">dk.napp.drawer</module>
        <module platform="iphone">com.acktie.mobile.ios.qr</module>
        <module platform="android">com.tripvi.drawerlayout</module>
        <module platform="android">br.com.arlsoft.pushclient</module>
        <module platform="iphone">br.com.arlsoft.pushclient</module>
        <module platform="iphone">ti.imagefactory</module>
        <module platform="android">ti.imagefactory</module>
        <module platform="android">ti.barcode</module>
        <module platform="iphone">ti.barcode</module>

**Comment by m1ga** [comment]
@mebarg which pushclient module are you using? This repo says its using ti.playservices in cause you are using a different one: https://github.com/deckameron/PushClient

**Comment by hansemannn** [comment]
Yep, it's indeed the [br.com.arlsoft.pushclient](https://github.com/deckameron/PushClient/blob/master/modules/android/android/manifest#L15) Android module causing the issue. Update to the one linked by @m1ga and push the vendor of the module to update it there as well, thx!
