### ISSUE TITLE
Using 11.8.0 app crashes

### ISSUE THREAD

**Issue by blantonl** [appcelerator-modules/ti.playservices#15]
Using 11.8.0 app won't launch and crashes with no error

-- Start application log -----------------------------------------------------
[INFO] :   MultiDex: VM with version 2.1.0 has multidex support
[INFO] :   MultiDex: Installing application
[INFO] :   MultiDex: VM has multidex support, MultiDex support library is disabled.

App then simply crashes

**Comment by garymathews** [comment]
What version of Google Play services do you have installed on your device?

**Comment by blantonl** [comment]
It is a Nexus 6P with the latest updates.  How do I check?

**Comment by hansemannn** [comment]
@garymathews Will 11.8.0 finally be supported in 8.0.0? Would be great for updating firebase as well - Ti is a bit behind there.

**Comment by hansemannn** [comment]
It was just updated to latest, thank you @garymathews and sorry for the pressure! Will test next week and update all Firebase modules. @blantonl This can be closed.
