### ISSUE TITLE
App crashed in runtime with Ti SDK 10.0.0

### ISSUE THREAD

**Issue by riodiep** [appcelerator-modules/ti.playservices#191]
When I added module Ti.Playservices in Tiapp.xml, the app compiled and opened but crashed at runtime with below error without hitting alloy.js . I have tried on version 17.1.1, 17.3.0 and 17.5.0. In version 16.1.3 compiling failed with error in Ti SDK 10

**Tiapp.xml**

`<modules>
<module platform="android">ti.playservices</module>
</modules>`

**Error**

`[ERROR] TiExceptionHandler: (main) [91,91] ti:/kroll.js:1045 [ERROR] TiExceptionHandler: throw new Error(Requested module not found: ${request}); // TODO Set 'code' property to 'MODULE_NOT_FOUND' to match Node? [ERROR] TiExceptionHandler: ^ [ERROR] TiExceptionHandler: Error: Requested module not found: ti.playservices\ti.playservices.bootstrap [ERROR] TiExceptionHandler: at Module.require (ti:/kroll.js:1045:14) [ERROR] TiExceptionHandler: at Module.global.Module.require (<embedded>:5086:32) [ERROR] TiExceptionHandler: at require (ti:/kroll.js:1315:22) [ERROR] TiExceptionHandler: at global.require (<embedded>:5071:10) [ERROR] TiExceptionHandler: at doLoad (<embedded>:11198:27) [ERROR] TiExceptionHandler: at loadBootstrapScripts (<embedded>:11224:5) [ERROR] TiExceptionHandler: at loadAsync (<embedded>:11229:3) [ERROR] TiExceptionHandler: at _startSnapshot (<embedded>:11246:1) [ERROR] TiExceptionHandler: at /ti.main.js:1:8 [ERROR] TiExceptionHandler: at Module._runScript (ti:/kroll.js:1342:24) [ERROR] TiExceptionHandler: [ERROR] TiExceptionHandler: org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method) [ERROR] TiExceptionHandler: org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:175) [ERROR] TiExceptionHandler: org.appcelerator.titanium.TiApplication.launch(TiApplication.java:868) [ERROR] TiExceptionHandler: org.appcelerator.titanium.TiLaunchActivity.loadScript(TiLaunchActivity.java:96) [ERROR] TiExceptionHandler: org.appcelerator.titanium.TiRootActivity.loadScript(TiRootActivity.java:497) [ERROR] TiExceptionHandler: org.appcelerator.titanium.TiLaunchActivity.onResume(TiLaunchActivity.java:177) [ERROR] TiExceptionHandler: org.appcelerator.titanium.TiRootActivity.onResume(TiRootActivity.java:516) [ERROR] TiExceptionHandler: android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453) [ERROR] TiExceptionHandler: android.app.Activity.performResume(Activity.java:7962) [ERROR] TiExceptionHandler: android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195) [ERROR] V8Exception: Exception occurred at ti:/kroll.js:1045: Uncaught Error: Requested module not found: ti.playservices\ti.playservices.bootstrap`

**Comment by ewanharris** [comment]
@riodiep it looks like you're hitting [this issue](https://jira.appcelerator.org/browse/TIMOB-28463) which is fixed in [this PR](https://github.com/appcelerator/titanium_mobile/pull/12860). Could you try downloading a 10_0_X CI build using `ti sdk install -b 10_0_X` and using that as it should contain the fix

**Comment by riodiep** [comment]
Thanks @ewanharris . It worked.
