### ISSUE TITLE
Module Not Found Error.

### ISSUE THREAD

**Issue by diogoamorim2** [appcelerator-modules/ti.playservices#2]
Hi,

I'm trying using this module but always return "module not found error", I follow the code example but the error still (put in Tiapp and require), I'm use  Win 10, SDK Ti 6.2.2.GA (The SDK Ti 6.3.1.GA describe in requirement doc I can't find). I'm donwloaded from [here](http://builds.appcelerator.com/#master) SDK 6.3.0.GA and 7.0.0 but the same problem it occurred.

**Comment by ulissesrsilva** [comment]
The same thing is happening to me :(

**Comment by m1ga** [comment]
Recompile the module with this manifest:
```
version: 1.0.1
apiversion: 3
architectures: armeabi-v7a x86
description: titanium-firebase-core
author: Hans Knoechel
license: Apache 2
copyright: Copyright (c) 2017 by Axway Appcelerator

# these should not be edited
name: titanium-firebase-core
moduleid: firebase.core
guid: ab3474fc-9923-4cda-a651-0dfc2ba3ad4c
platform: android
minsdk: 6.0.0
```

then you can include it in a 6.3.0.GA project with

```xml
<modules>
    <module>ti.playservices</module>
  </modules>
```
in tiapp.xml

**Comment by hansemannn** [comment]
Please note that the duplicate-library-detection (a change in the CLI) still requires 7.0.0 - or patch your local 6.3.0 with [this PR](https://github.com/appcelerator/titanium_mobile/pull/9481) if you are running into issues!
