### ISSUE TITLE
Access Play Services Functions

### ISSUE THREAD

**Issue by raybelisle** [appcelerator-modules/ti.playservices#5]
Since it looks like all of the play services libraries are included, what is the method to instantiate an instance of a service? For example, play-services-location-11.0.4.aar is included, but how would you create then reference the API calls from that aar?

**Comment by hansemannn** [comment]
The PlayServices represent the base libraries used in many (other) Android API's, like FusedLocation for play-services-location. Once included, you can access classes like `com.google.android.gms.location.FusedLocationProviderClient` in classic modules and Hyperloop.
