### ISSUE TITLE
How can I install as a module in my project?

### ISSUE THREAD

**Issue by argum** [appcelerator-modules/ti.playservices#6]
Do I have to compile this module? I try to install the zip as a module but the module does not appears in the module "add" list button.

Thanks!

**Comment by chmiiller** [comment]
Which version of the Titanium SDK are you in? Because if the module has minSdkVersion bigger than your current Titanium SDK, you might not see the "add" button

**Comment by Topener** [comment]
If you're using the latest TiSDK's you don't have to download it, it should just appear in the list of modules already

**Comment by hansemannn** [comment]
Thanks @chmiiller & @Topener, thats right! In any case, you should use this module in Titanium SDK 7+ only to make use of the resolve PlayServices conflicts. If it still does not appear in the list, check if the tiapp.xml <version> is set to SDK 7 or later or open a bug on jira.appcelerator.org. Thanks!
