### ISSUE TITLE
Using within an existing Ti Native Module

### ISSUE THREAD

**Issue by benbahrenburg** [appcelerator-modules/ti.playservices#7]
Thanks for putting this together.  Is there any examples on how to use this as a dependency within a native module. I see that the Ti.Map uses this as a dependency but I can't figure out how to add the module or it's lib dependencies to my path.

Would be great to have all of the module developers use a common source for Google Play Services. But, need alittle help on how to reference the module from within Eclipse.

**Comment by hansemannn** [comment]
We will document this over the upcoming week as we are getting closer to the RC. Basically, you can require it via the `timodule.xml`, like [here](https://github.com/appcelerator-modules/ti.map/blob/master/android/timodule.xml#L11-L13):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ti:module xmlns:ti="http://ti.appcelerator.org" xmlns:android="http://schemas.android.com/apk/res/android">
    <android xmlns:android="http://schemas.android.com/apk/res/android">
        <manifest />
    </android>
    <modules>
        <module platform="android">ti.playservices</module>
   </modules>
</ti:module>
```

**Comment by benbahrenburg** [comment]
Thanks @hansemannn will wait for the documentation.  Where I'm running into the issue us that once I remove the references in Eclipse everything is invalid.  Maybe it makes sense to have everyone use the Google Play Jar and just not bundle?

Will wait for more guidance next week.  Thanks for your help with all of this.

**Comment by zarir** [comment]
@hansemannn Any update on this?

**Comment by hansemannn** [comment]
@garymathews Can you help here? I'm on vacation right now.

**Comment by benbahrenburg** [comment]
@garymathews @hansemannn  is the proper way to integrate ti.playservices with an existing native module to do the following:

1.  Add ti.playservices to the modules.xml
2.  Unzip the aar files that we are using and add them as jars into our Eclipse module project
3.  The Ti project will then remove any duplicates between the aar files from Ti.playservices and the jar files from the module project

Wanted to confirm the workflow before trying to incorporate the new approach into the different native modules I maintain.

**Comment by garymathews** [comment]
@benbahrenburg Nearly, when developing your native module include the `*.jar`'s as necessary to resolve references in your IDE. However, once developed be sure to not leave any playservices specific `*.jar`'s laying around your Titanium module as they could conflict with the included `.aar`'s from `ti.playservices`

**Comment by deckameron** [comment]
@hansemannn Any update on this?

**Comment by hansemannn** [comment]
@deckameron See @garymathews answer above. I forgot to close it

**Comment by deckameron** [comment]
Thank you @hansemannn!
I tried his suggestion but I got no luck. I thought something was still missing, but could not tell what it was.

I managed to get it working on device only, but never on genymotion emulator with GApps.
