### ISSUE TITLE
Google Play Services Version?

### ISSUE THREAD

**Issue by benbahrenburg** [appcelerator-modules/ti.playservices#8]
Is it possible to include in the manifest or other file the version of the Google PlayServices jar?

This would help us module developers in figuring out what version we should link against.

**Comment by hansemannn** [comment]
Right now we indicate the version via the manifest `version` property, see [here](https://github.com/appcelerator-modules/ti.playservices/blob/master/android/manifest#L5). It may make sense to list it as an own key, so bug-fixes or other changes to the module itself don't cause mixed versions.

**Comment by hansemannn** [comment]
After talking to the Android team, this is now more clear: We use the last part of the last semver part of the version to specify bugfixes. Example: The current version the module is `11.0.40`, which is `11.0.4` + no bugfix. If there is a bug in the Titanium module, the next version would be `11.0.41`. And in case Android has more than 9 fix versions per feature version, the next bugfix-version from a Ti perspective would be `11.0.101`.

I hope this is more clear now! We know that it may look weird, but it gives developers the huge advantage to see the actual play services version without manually extracting the used aar's and for us to not needing to change the readme for every release.
